#!/usr/bin/env fish

# Automatically generated by Boxen. Don't edit directly. This file
# sets up paths and basic environment for the Boxen dev environment,
# and is intended to be sourced in your shell profile.

# set +e
# set +u

# Make the root of Boxen available.

set -x BOXEN_HOME /opt/boxen

# Add any binaries specific to Boxen to the path.

set -x PATH $BOXEN_HOME/bin $PATH

###### PARSE ERR: for f in $BOXEN_HOME/env.d/*.sh ; do
###### PARSE ERR:   if [ -f $f ] ; then
###### PARSE ERR:     source $f
###### PARSE ERR:   fi
###### PARSE ERR: done

# Boxen is active.

###### PARSE ERR: if [ -d "$BOXEN_HOME/repo/.git" ]; then
set -x BOXEN_SETUP_VERSION (env GIT_DIR=$BOXEN_HOME/repo/.git git rev-parse --short HEAD)
###### PARSE ERR: else
###### PARSE ERR:   echo "Boxen could not load properly!"
###### PARSE ERR: fi
set -x HOMEBREW_CASK_OPTS "--caskroom=/opt/homebrew-cask/Caskroom"
# Expose basic setup paths. BOXEN_HOME is already exported at the top level.

set -x BOXEN_BIN_DIR /opt/boxen/bin
set -x BOXEN_CONFIG_DIR /opt/boxen/config
set -x BOXEN_DATA_DIR /opt/boxen/data
set -x BOXEN_ENV_DIR /opt/boxen/env.d
set -x BOXEN_LOG_DIR /opt/boxen/log
set -x BOXEN_SOCKET_DIR /opt/boxen/data/project-sockets
set -x BOXEN_SRC_DIR /Users/harvand/src

# Expose boxen's binary download location
set -x BOXEN_DOWNLOAD_URL_BASE http://boxen-downloads.s3.amazonaws.com
set -x HOMEBREW_ROOT /usr/local
set -x HOMEBREW_CACHE /opt/boxen/cache/homebrew

set -x BOXEN_HOMEBREW_BOTTLE_URL http://boxen-downloads.s3.amazonaws.com/homebrew


set -x CFLAGS "-I$HOMEBREW_ROOT/include"



set -x LDFLAGS "-L$HOMEBREW_ROOT/lib"


# Add homebrew'd stuff to the path.

set -x PATH $HOMEBREW_ROOT/bin $HOMEBREW_ROOT/sbin $PATH

# Add homebrew'd stuff to the manpath.

#set -x MANPATH $HOMEBREW_ROOT/share/man $MANPATH
# Expose GitHub credentials

set -x BOXEN_GITHUB_LOGIN mootpointer
# Put nodenv on PATH
set -x PATH /opt/boxen/nodenv/bin $PATH

# Configure NODENV_ROOT and put NODENV_ROOT/bin on PATH
set -x NODENV_ROOT /opt/boxen/nodenv
set -x PATH $NODENV_ROOT/bin $PATH

# Load nodenv
###### PARSE ERR: eval "$(nodenv init -)"

# Helper for shell prompts and the like
###### PARSE ERR: current_node() {
###### PARSE ERR:   echo "$(nodenv version-name)"
###### PARSE ERR: }
set -x PYENV_ROOT /opt/boxen/pyenv

set -x PATH /opt/boxen/pyenv/bin $PATH

###### PARSE ERR: eval "$(pyenv init -)"
# Put ruby-build on PATH
set -x PATH /opt/boxen/ruby-build/bin $PATH

# Allow bundler to use all the cores for parallel installation
set -x BUNDLE_JOBS 8

# Configure RBENV_ROOT and put RBENV_ROOT/bin on PATH
set -x RBENV_ROOT /opt/boxen/rbenv
set -x PATH $RBENV_ROOT/bin $PATH

# Load rbenv
###### PARSE ERR: eval "$(rbenv init -)"

# Helper for shell prompts and the like
###### PARSE ERR: current-ruby() {
###### PARSE ERR:   echo "$(rbenv version-name)"
###### PARSE ERR: }

# Make all the fancy `hub` shortcuts available via `git`.

eval (/usr/local/bin/hub alias -s)

# Postgres config vars

set -x BOXEN_POSTGRESQL_HOST 127.0.0.1
set -x BOXEN_POSTGRESQL_PORT 15432
set -x BOXEN_POSTGRESQL_URL "postgres://$BOXEN_POSTGRESQL_HOST:$BOXEN_POSTGRESQL_PORT/"

# soft global overrides
# set -x [ -z "$PGPORT" ]; and export PGPORT $BOXEN_POSTGRESQL_PORT
# Autocomplete for boxen


###### PARSE ERR: type complete >/dev/null && complete -C /opt/boxen/repo/modules/boxen/lib/boxen/autocomplete.rb -o default boxen
# Add ./bin to the path. This happens after initialization to make
# sure local stubs take precedence over stuff like rbenv.

set -x PATH bin $PATH
# Let the env know where Redis runs.

set -x BOXEN_REDIS_PORT 16379
set -x BOXEN_REDIS_URL "redis://localhost:$BOXEN_REDIS_PORT/"
set -x PATH /opt/boxen/rbenv/shims /opt/boxen/rbenv/bin $PATH
rbenv rehash 2>/dev/null
function git ; hub $argv ; end
